import type { ImageStyleDimensionGroup, ImageStyleDimensionOption, ImageStyleFragments, ImageStyleGenre, ImageStylePreset, ImageStyleSelection, ImageStyleSource } from "@/types/image-style";

export const IMAGE_STYLE_SOURCE_REPOSITORY = "https://github.com/ddt080701-eng/oscar-director-skill";
export const IMAGE_STYLE_SOURCE_COMMIT = "30463aead09ccb5e93e5bced8fcc420e917a81d6";
export const IMAGE_STYLE_CATALOG_VERSION = "1.0.0";

export const IMAGE_STYLE_SOURCE: ImageStyleSource = {
    repository: IMAGE_STYLE_SOURCE_REPOSITORY,
    commit: IMAGE_STYLE_SOURCE_COMMIT,
    section: "director visual language, genre guides, and practical film-look guide",
};

const version = IMAGE_STYLE_CATALOG_VERSION;

function fragments(input: Partial<ImageStyleFragments>): ImageStyleFragments {
    return {
        composition: [],
        palette: [],
        lighting: [],
        lens: [],
        texture: [],
        atmosphere: [],
        ...input,
    };
}

/**
 * Attribute-only cinematography recipes distilled from the referenced skill.
 * `inspiration` is intentionally metadata for attribution/UI and is never
 * read by the prompt compiler.
 */
const BASE_IMAGE_STYLE_PRESETS = [
    {
        id: "cold-symmetry",
        label: "冷峻对称",
        family: "cinematography",
        inspiration: "受 Stanley Kubrick 的几何秩序与冷峻空间启发",
        tags: ["对称", "几何", "冷灰", "深焦"],
        fragments: fragments({
            composition: ["precise central symmetry", "vanishing-point composition", "controlled geometric blocking"],
            palette: ["cool gray palette", "muted neutrals", "a small controlled red accent"],
            lighting: ["hard directional practical light", "clean shadow edges", "high tonal control"],
            lens: ["wide-angle perspective", "locked-off camera", "deep focus"],
            texture: ["subtle 35mm film grain", "crisp production design"],
            atmosphere: ["quiet tension", "formal restrained mood"],
        }),
        avoid: ["random visual clutter", "soft beauty retouching", "excessive lens flare"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / geometric composition" },
    },
    {
        id: "warm-natural-depth",
        label: "暖光深景",
        family: "cinematography",
        inspiration: "受 Steven Spielberg 的自然暖光与情绪叙事启发",
        tags: ["暖光", "自然", "叙事", "景深"],
        fragments: fragments({
            composition: ["layered foreground, middle ground, and background", "eye-level narrative framing", "clear subject staging"],
            palette: ["warm natural earth tones", "gentle golden highlights", "balanced skin tones"],
            lighting: ["motivated natural light", "soft backlight", "subtle practical glow"],
            lens: ["moderate wide lens", "smooth dolly movement", "selective deep focus"],
            texture: ["natural skin texture", "fine organic film grain"],
            atmosphere: ["human warmth", "emotionally accessible storytelling"],
        }),
        avoid: ["sterile studio lighting", "flat isolated staging", "over-processed skin"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / natural light and staging" },
    },
    {
        id: "cold-negative-space",
        label: "冷蓝负空间",
        family: "cinematography",
        inspiration: "受 Denis Villeneuve 的冷蓝灰色调与宏大负空间启发",
        tags: ["冷蓝", "负空间", "雾霭", "宏大"],
        fragments: fragments({
            composition: ["expansive negative space", "small subject against monumental surroundings", "deliberate horizon placement"],
            palette: ["cold blue-gray palette", "desaturated steel tones", "restrained amber contrast"],
            lighting: ["diffused overcast light", "volumetric haze", "soft atmospheric backlight"],
            lens: ["wide cinematic lens", "slow deliberate camera movement", "deep environmental focus"],
            texture: ["fine grain", "weathered tactile surfaces"],
            atmosphere: ["meditative scale", "quiet existential tension", "spare visual rhythm"],
        }),
        avoid: ["cheerful saturated colors", "busy backgrounds", "cartoon-like lighting"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / scale, color, and atmosphere" },
    },
    {
        id: "pastel-symmetry",
        label: "粉彩正面",
        family: "cinematography",
        inspiration: "受 Wes Anderson 的正面构图、粉彩色彩与舞台化布景启发",
        tags: ["粉彩", "正面", "对称", "舞台感"],
        fragments: fragments({
            composition: ["front-facing symmetrical framing", "centered subject placement", "carefully ordered frame-within-frame"],
            palette: ["soft pastel palette", "muted peach, mint, and butter tones", "coordinated color blocking"],
            lighting: ["even soft frontal light", "gentle shadow definition", "storybook clarity"],
            lens: ["normal lens with minimal distortion", "static tableau camera", "precise lateral movement"],
            texture: ["slightly tactile paper-like texture", "subtle analog grain"],
            atmosphere: ["playful deadpan mood", "deliberate theatrical staging"],
        }),
        avoid: ["messy asymmetry", "harsh modern grading", "unmotivated camera shake"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / symmetry and color design" },
    },
    {
        id: "neon-urban-energy",
        label: "霓虹都市",
        family: "cinematography",
        inspiration: "受 Martin Scorsese 的城市夜景、霓虹色彩与人物动势启发",
        tags: ["霓虹", "夜景", "都市", "动势"],
        fragments: fragments({
            composition: ["dynamic off-center framing", "layered urban depth", "observational street-level staging"],
            palette: ["neon cyan and warm red contrast", "deep urban blacks", "selective saturated highlights"],
            lighting: ["mixed practical neon light", "hard side light with motivated sources", "reflected street glow"],
            lens: ["documentary 35mm perspective", "fluid tracking movement", "occasional kinetic close-up"],
            texture: ["wet pavement reflections", "visible but restrained film grain"],
            atmosphere: ["restless nocturnal energy", "gritty human immediacy"],
        }),
        avoid: ["empty showroom cleanliness", "uniform flat illumination", "plastic CGI surfaces"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / urban night and camera movement" },
    },
    {
        id: "social-color-contrast",
        label: "阶层色彩对比",
        family: "cinematography",
        inspiration: "受 Bong Joon-ho 的空间分层与色彩叙事启发",
        tags: ["空间分层", "冷暖对比", "社会寓言", "深景"],
        fragments: fragments({
            composition: ["clear vertical and horizontal spatial hierarchy", "deep staging with foreground obstacles", "contrasting parallel spaces"],
            palette: ["cool lower tones against selective warm upper tones", "controlled social color coding", "muted overall saturation"],
            lighting: ["motivated contrast between natural and artificial light", "architectural shadow lines", "precise practical sources"],
            lens: ["wide lens for spatial relationships", "measured push-in", "deep focus blocking"],
            texture: ["concrete, glass, and fabric tactility", "clean contemporary grain"],
            atmosphere: ["quiet social tension", "darkly ironic restraint"],
        }),
        avoid: ["ambiguous spatial logic", "random color noise", "generic luxury gloss"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / space and color coding" },
    },
    {
        id: "blue-orange-epic",
        label: "蓝橙史诗",
        family: "cinematography",
        inspiration: "受 Christopher Nolan 的冷蓝灰与暖橙光源对照启发",
        tags: ["蓝橙", "史诗", "高反差", "宽银幕"],
        fragments: fragments({
            composition: ["wide epic composition", "strong foreground-to-background scale", "clean graphic silhouettes"],
            palette: ["cool blue-gray shadows", "restrained warm orange practicals", "steel and amber contrast"],
            lighting: ["high-contrast directional light", "backlit atmosphere", "controlled flare from practical sources"],
            lens: ["large-format wide perspective", "steady forward movement", "deep environmental focus"],
            texture: ["subtle large-format grain", "crisp physical detail"],
            atmosphere: ["monumental urgency", "grounded practical realism"],
        }),
        avoid: ["overly glossy superhero styling", "excessive bloom", "unmotivated color gradients"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / epic scale and color contrast" },
    },
    {
        id: "surreal-organic-shadow",
        label: "暗黑奇幻",
        family: "cinematography",
        inspiration: "受 Guillermo del Toro 的有机材质、阴影与童话式暗黑氛围启发",
        tags: ["暗黑", "奇幻", "有机材质", "阴影"],
        fragments: fragments({
            composition: ["storybook frame-within-frame", "off-kilter but intentional perspective", "symbolic foreground props"],
            palette: ["deep teal and rust palette", "muted jewel tones", "warm isolated highlights"],
            lighting: ["sculpted chiaroscuro", "moody side light", "soft shafts through haze"],
            lens: ["close wide-angle intimacy", "slow creeping camera", "selective focus on tactile details"],
            texture: ["organic wood, metal, and fabric detail", "fine cinematic grain"],
            atmosphere: ["poetic unease", "dark fairy-tale wonder"],
        }),
        avoid: ["clean commercial polish", "flat front light", "random horror gore"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / fantasy texture and light" },
    },
    {
        id: "handheld-humanist",
        label: "手持纪实",
        family: "cinematography",
        inspiration: "受 Alfonso Cuarón 的自然光、长镜头与贴近人物的观察感启发",
        tags: ["手持", "纪实", "自然光", "长镜头"],
        fragments: fragments({
            composition: ["immersive human-scale framing", "unobtrusive observational composition", "foreground elements passing through frame"],
            palette: ["natural low-saturation colors", "soft daylight neutrals", "true-to-life skin tones"],
            lighting: ["available light", "soft window light", "natural exposure falloff"],
            lens: ["handheld 35mm viewpoint", "long-take feeling", "gentle focus transitions"],
            texture: ["authentic skin and surface texture", "subtle documentary grain"],
            atmosphere: ["intimate immediacy", "quietly observed emotion"],
        }),
        avoid: ["over-stabilized perfection", "beauty-filter skin", "artificial studio backdrop"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / long take and naturalism" },
    },
    {
        id: "expressive-color-movement",
        label: "表现主义动势",
        family: "cinematography",
        inspiration: "受 Damien Chazelle 的高饱和舞台色彩与音乐性运动启发",
        tags: ["高饱和", "舞台", "运动", "节奏"],
        fragments: fragments({
            composition: ["bold diagonal composition", "rhythmic subject placement", "expressive transitions between wide and close framing"],
            palette: ["rich primary color accents", "warm amber against deep blue", "controlled theatrical saturation"],
            lighting: ["motivated stage spotlights", "colored rim light", "strong pools of illumination"],
            lens: ["fluid sweeping camera movement", "energetic tracking shot", "musical close-up timing"],
            texture: ["clean theatrical detail", "light analog grain"],
            atmosphere: ["romantic ambition", "kinetic performance energy"],
        }),
        avoid: ["lifeless static staging", "uncontrolled rainbow colors", "generic music-video gloss"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / color, rhythm, and movement" },
    },
    {
        id: "quiet-long-take",
        label: "静默长镜头",
        family: "cinematography",
        inspiration: "受 Yorgos Lanthimos 的克制表演、留白与疏离构图启发",
        tags: ["留白", "疏离", "长镜头", "克制"],
        fragments: fragments({
            composition: ["spare negative space", "rigid frontal or distant framing", "deliberate awkward spatial distance"],
            palette: ["cool desaturated neutrals", "pale institutional colors", "small unexpected color accent"],
            lighting: ["flat controlled daylight", "subtle overhead practicals", "emotionally detached illumination"],
            lens: ["moderate telephoto compression", "slow unbroken camera movement", "static observational takes"],
            texture: ["clean restrained detail", "barely visible grain"],
            atmosphere: ["deadpan unease", "quiet absurdity", "emotional restraint"],
        }),
        avoid: ["melodramatic expressions", "excessive handheld shake", "overly sentimental glow"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / restraint and framing" },
    },
    {
        id: "weathered-samurai",
        label: "风雨武士",
        family: "cinematography",
        inspiration: "受 Akira Kurosawa 的天气元素、动作调度与高低调对比启发",
        tags: ["风雨", "动作", "高反差", "群像"],
        fragments: fragments({
            composition: ["movement-based action framing", "layered diagonal blocking", "clear group silhouettes"],
            palette: ["earth reds and weathered neutrals", "controlled color-coded groups", "restrained saturation"],
            lighting: ["weather as a lighting element", "hard sun broken by rain or fog", "high-key to low-key contrast"],
            lens: ["telephoto compression of action", "decisive multi-angle coverage", "wide battlefield establishing view"],
            texture: ["rain, wind, dust, and worn fabric detail", "organic film grain"],
            atmosphere: ["epic moral clarity", "urgent physical momentum"],
        }),
        avoid: ["weightless action posing", "clean studio weather", "random costume color noise"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / weather and action composition" },
    },
    {
        id: "raw-wilderness",
        label: "荒野生存",
        family: "cinematography",
        inspiration: "受 Alejandro González Iñárritu 的自然光、沉浸式连续性与荒野质感启发",
        tags: ["荒野", "自然光", "沉浸", "生存"],
        fragments: fragments({
            composition: ["immersive subjective framing", "pseudo-single-take continuity", "close emotional proximity"],
            palette: ["cold natural desaturation", "earth and snow neutrals", "restrained skin-tone warmth"],
            lighting: ["fully motivated natural light", "cold overcast exposure", "raw directional daylight"],
            lens: ["large-format perspective", "close wide-angle intimacy", "gentle focus breathing"],
            texture: ["wet skin, mud, frost, and worn surfaces", "raw fine-grain detail"],
            atmosphere: ["visceral survival pressure", "immersive physical reality"],
        }),
        avoid: ["polished fashion styling", "artificial rim-light spectacle", "clean untouched wilderness"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / natural light and survival immersion" },
    },
    {
        id: "intimate-monochrome",
        label: "灵魂特写",
        family: "cinematography",
        inspiration: "受 Ingmar Bergman 的面部特写、诚实之光与存在主义留白启发",
        tags: ["黑白", "面部", "心理", "极简"],
        fragments: fragments({
            composition: ["extreme facial close-up", "two faces sharing a tense frame", "minimal psychological staging"],
            palette: ["high-contrast black and white", "soft Nordic gray scale", "deep controlled blacks"],
            lighting: ["honest natural light", "soft bounced facial modeling", "quiet directional falloff"],
            lens: ["intimate portrait perspective", "shallow focus on eyes and skin", "static contemplative camera"],
            texture: ["visible pores and authentic skin texture", "subtle archival grain"],
            atmosphere: ["existential minimalism", "psychological intensity", "unresolved silence"],
        }),
        avoid: ["beauty retouching", "sentimental soft glow", "busy dramatic background"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / face, light, and psychological framing" },
    },
    {
        id: "panoramic-epic",
        label: "壮阔景观",
        family: "cinematography",
        inspiration: "受 David Lean 的超宽画幅、景观叙事与长焦压缩启发",
        tags: ["宽银幕", "景观", "史诗", "长焦"],
        fragments: fragments({
            composition: ["sweeping widescreen establishing shot", "humans dwarfed by geological scale", "horizon-led visual design"],
            palette: ["golden desert and aged earth tones", "sun-bleached highlights", "restrained historical color"],
            lighting: ["golden-hour natural light", "atmospheric haze and dust", "sculpted landscape shadows"],
            lens: ["large-format panoramic perspective", "custom telephoto compression", "slow composed camera movement"],
            texture: ["wind-shaped sand, stone, and fabric detail", "subtle 70mm film grain"],
            atmosphere: ["historical epic grandeur", "landscape as a narrative character"],
        }),
        avoid: ["tiny cluttered horizon", "flat digital landscape", "modern commercial gloss"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "director visual language / landscape and epic scale" },
    },
] satisfies readonly ImageStylePreset[];

function directorPreset(input: { id: string; label: string; inspiration: string; tags: readonly string[]; fragments: Partial<ImageStyleFragments>; avoid: readonly string[] }): ImageStylePreset {
    return {
        id: input.id,
        label: input.label,
        family: "cinematography",
        inspiration: input.inspiration,
        tags: input.tags,
        fragments: fragments(input.fragments),
        avoid: input.avoid,
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: `director visual language / ${input.id}` },
    };
}

/** The remaining director entries from the source skill, kept attribute-only. */
const ADDITIONAL_IMAGE_STYLE_PRESETS: readonly ImageStylePreset[] = [
    directorPreset({
        id: "alfred-hitchcock",
        label: "悬念窥视",
        inspiration: "受 Alfred Hitchcock 的限制空间、主观视角与心理悬念启发",
        tags: ["悬念", "窥视", "限制空间"],
        fragments: {
            composition: ["confined framing", "door, window, and mirror framing", "subjective point of view"],
            palette: ["desaturated cool tones", "restrained monochrome"],
            lighting: ["high-contrast chiaroscuro", "venetian-blind shadow patterns", "isolated pools of light"],
            lens: ["dolly zoom perspective", "measured slow push-in", "subjective perspective"],
            texture: ["classic 35mm film grain", "crisp noir detail"],
            atmosphere: ["suspenseful voyeuristic unease", "dramatic irony", "psychological tension"],
        },
        avoid: ["open cheerful staging", "flat fill light", "unmotivated spectacle"],
    }),
    directorPreset({
        id: "orson-welles",
        label: "深焦权力",
        inspiration: "受 Orson Welles 的深焦、多层叙事与极端低角度启发",
        tags: ["深焦", "低角度", "权力"],
        fragments: {
            composition: ["deep-focus layered staging", "extreme low-angle framing", "visible ceiling perspective"],
            palette: ["high-contrast black-and-white", "muted monochrome"],
            lighting: ["hard sculptural key light", "deep power shadows"],
            lens: ["wide-angle deep focus", "extreme low-angle perspective"],
            texture: ["high-contrast 35mm grain", "optical composite texture"],
            atmosphere: ["political power", "layered nonlinear mystery", "ominous authority"],
        },
        avoid: ["shallow isolated staging", "soft commercial light", "weightless composition"],
    }),
    directorPreset({
        id: "john-ford",
        label: "边疆纪碑",
        inspiration: "受 John Ford 的纪念碑式景观、门框与地平线系统启发",
        tags: ["西部", "地平线", "荒野"],
        fragments: {
            composition: ["monumental valley vista", "doorway framing between civilization and wilderness", "low or high horizon system"],
            palette: ["red sandstone and ochre earth tones", "muted frontier colors"],
            lighting: ["hard western sunlight", "golden-hour side light", "long landscape shadows"],
            lens: ["wide establishing perspective", "panoramic landscape framing"],
            texture: ["dusty weathered surfaces", "restrained 35mm grain"],
            atmosphere: ["frontier solitude", "monumental wilderness", "civilization-versus-wild tension"],
        },
        avoid: ["crowded horizon", "glossy modern surfaces", "flat studio backdrop"],
    }),
    directorPreset({
        id: "federico-fellini",
        label: "梦境马戏",
        inspiration: "受 Federico Fellini 的漂浮镜头、戏剧化调度与梦境色彩启发",
        tags: ["梦境", "马戏", "漂浮"],
        fragments: {
            composition: ["theatrical tableau staging", "high-angle aerial viewpoint", "expressive face-centered framing"],
            palette: ["dreamlike saturated accents", "emotionally coded colors"],
            lighting: ["soft theatrical key light", "isolated spotlight pools"],
            lens: ["floating camera movement", "graceful crane perspective", "wide dream lens"],
            texture: ["vintage film grain", "tactile theatrical costumes and sets"],
            atmosphere: ["surreal circus energy", "subjective dream logic", "grotesque whimsy"],
        },
        avoid: ["sterile realism", "generic corporate staging", "flat emotionless palette"],
    }),
    directorPreset({
        id: "francis-coppola",
        label: "歌剧权力",
        inspiration: "受 Francis Ford Coppola 的歌剧化权力、战争幻觉与象征道具启发",
        tags: ["歌剧化", "战争", "权力"],
        fragments: {
            composition: ["power-centered framing", "layered jungle staging", "symbolic foreground props"],
            palette: ["jungle green, destructive orange-red, and deathly blue", "controlled triadic color script"],
            lighting: ["expressive top light", "flare and smoke-filtered beams", "high-contrast chiaroscuro"],
            lens: ["immersive wide perspective", "slow deliberate tracking"],
            texture: ["humid haze", "dense organic surfaces", "smoke-softened film grain"],
            atmosphere: ["operatic power", "hallucinatory war tension", "moral descent"],
        },
        avoid: ["lighthearted commercial tone", "clean untouched environments", "random color noise"],
    }),
    directorPreset({
        id: "billy-wilder",
        label: "黑色讽刺",
        inspiration: "受 Billy Wilder 的古典叙事、黑色光影与都市疏离启发",
        tags: ["黑色电影", "讽刺", "都市"],
        fragments: {
            composition: ["clear classical narrative staging", "grid-like office geometry", "frame-within-frame"],
            palette: ["high-contrast monochrome", "muted noir amber"],
            lighting: ["low-key hard light", "venetian-blind shadows", "deep urban contrast"],
            lens: ["precise normal-lens perspective", "static composed camera"],
            texture: ["crisp classic film grain", "aged urban surfaces"],
            atmosphere: ["cynical wit", "modern alienation", "gothic decay"],
        },
        avoid: ["soft glamour retouching", "cheerful flat lighting", "generic stock-photo polish"],
    }),
    directorPreset({
        id: "coen-brothers",
        label: "荒诞留白",
        inspiration: "受 Coen Brothers 的荒诞留白、孤立人物与冷峻空间启发",
        tags: ["荒诞", "留白", "冷峻"],
        fragments: {
            composition: ["expansive negative space", "isolated figure against a stark horizon", "sparse environmental staging"],
            palette: ["desaturated snow and earth tones", "restrained blood-red accent"],
            lighting: ["flat overcast daylight", "hard winter contrast"],
            lens: ["wide environmental perspective", "static observational framing"],
            texture: ["snow, dust, and worn material tactility", "restrained cinematic grain"],
            atmosphere: ["bleak absurdism", "moral emptiness", "lonely stillness"],
        },
        avoid: ["busy colorful staging", "sentimental glow", "polished luxury surfaces"],
    }),
    directorPreset({
        id: "ridley-scott",
        label: "工业黑暗",
        inspiration: "受 Ridley Scott 的工业美术、霓虹雨夜与体积光启发",
        tags: ["工业", "霓虹", "体积光"],
        fragments: {
            composition: ["painterly production-design tableau", "monumental industrial spaces", "deep layered staging"],
            palette: ["dark steel with neon cyan and amber", "gold-and-blue contrast"],
            lighting: ["high-contrast volumetric beams", "practical neon and rain reflections", "smoke-filtered light"],
            lens: ["wide anamorphic perspective", "slow atmospheric camera movement", "deep focus"],
            texture: ["wet metal, steam, and rain", "tactile production-design detail"],
            atmosphere: ["dystopian noir", "industrial awe", "oppressive weather"],
        },
        avoid: ["clean daylight showroom", "flat untextured CGI", "random neon overload"],
    }),
    directorPreset({
        id: "james-cameron",
        label: "沉浸奇观",
        inspiration: "受 James Cameron 的沉浸式探索、互补色与生物荧光启发",
        tags: ["奇观", "探索", "荧光"],
        fragments: {
            composition: ["immersive wide exploration", "environmental scale with dynamic foreground", "clear subject-to-world relationship"],
            palette: ["strong complementary color contrast", "bioluminescent cyan and warm amber", "deep ocean blue"],
            lighting: ["emissive practical light", "volumetric underwater shafts", "motivated environmental sources"],
            lens: ["smooth exploratory camera", "large-format widescreen perspective", "fluid movement"],
            texture: ["high-fidelity physical detail", "water and organic surface texture", "clean large-format clarity"],
            atmosphere: ["immersive adventure", "technological wonder", "elemental emotion"],
        },
        avoid: ["flat cardboard environments", "weightless plastic surfaces", "unmotivated color effects"],
    }),
    directorPreset({
        id: "ang-lee",
        label: "含蓄诗意",
        inspiration: "受 Ang Lee 的克制表演、跨文化意境与稳定中景启发",
        tags: ["含蓄", "水墨", "诗意"],
        fragments: {
            composition: ["restrained balanced medium framing", "stable close-up staging", "lyrical landscape composition"],
            palette: ["ink-wash greens and earth tones", "cool ocean blue", "delicate complementary hues"],
            lighting: ["soft natural light", "gentle atmospheric haze"],
            lens: ["stable medium telephoto", "high-frame-rate clarity", "widescreen perspective"],
            texture: ["fine natural grain", "tactile bamboo, water, and fabric"],
            atmosphere: ["contemplative intimacy", "cross-cultural lyricism", "quiet emotional restraint"],
        },
        avoid: ["overwrought camera tricks", "plastic skin", "empty spectacle"],
    }),
    directorPreset({
        id: "peter-jackson",
        label: "史诗造境",
        inspiration: "受 Peter Jackson 的史诗景观、实景特效与世界构建启发",
        tags: ["史诗", "造境", "动作"],
        fragments: {
            composition: ["sweeping epic landscape", "layered battle staging", "hero-to-scale framing"],
            palette: ["saturated natural greens and earth tones", "dramatic warm-cool contrast"],
            lighting: ["golden natural light", "atmospheric smoke and dust", "practical-effects illumination"],
            lens: ["large-format wide perspective", "aerial establishing shot", "dynamic tracking"],
            texture: ["tactile practical makeup and props", "weathered surfaces", "cinematic grain"],
            atmosphere: ["mythic adventure", "immersive world-building", "heroic momentum"],
        },
        avoid: ["empty green-screen look", "weightless props", "generic game-rendered surfaces"],
    }),
    directorPreset({
        id: "jane-campion",
        label: "荒野心理",
        inspiration: "受 Jane Campion 的建筑式取框、荒野心理与克制感官启发",
        tags: ["荒野", "心理", "取框"],
        fragments: {
            composition: ["architectural framing", "enclosed negative space", "face-and-landscape visual rhyme"],
            palette: ["muted gray-green", "muddy earth tones", "restrained natural colors"],
            lighting: ["high-contrast exterior light", "precise sun-shadow mapping"],
            lens: ["composed medium telephoto", "quiet static perspective"],
            texture: ["muddy tactile surfaces", "fine organic grain"],
            atmosphere: ["psychological wilderness", "sensual restraint", "austere tension"],
        },
        avoid: ["romanticized landscape gloss", "bright commercial palette", "unmotivated camera movement"],
    }),
    directorPreset({
        id: "chloe-zhao",
        label: "自然漂泊",
        inspiration: "受 Chloé Zhao 的魔幻时刻自然光、手持长焦与漂泊感启发",
        tags: ["自然光", "漂泊", "纪实"],
        fragments: {
            composition: ["observational human-scale framing", "subject compressed against landscape", "open negative space"],
            palette: ["natural subdued earth tones", "sun-washed dusk colors"],
            lighting: ["available natural light", "magic-hour glow", "unmodified exposure variation"],
            lens: ["handheld long-lens compression", "gentle 35mm roaming perspective"],
            texture: ["authentic everyday surfaces", "light documentary grain"],
            atmosphere: ["spontaneous naturalism", "solitary freedom", "quiet dignity"],
        },
        avoid: ["fashion-editorial posing", "artificial studio light", "over-polished skin"],
    }),
    directorPreset({
        id: "daniels",
        label: "多元宇宙",
        inspiration: "受 Daniels 的多元格式切换、互联网拼贴与荒诞温情启发",
        tags: ["多元宇宙", "拼贴", "荒诞"],
        fragments: {
            composition: ["abrupt cross-universe format shifts", "high-density playful framing", "impossible perspective changes"],
            palette: ["radically shifting universe palettes", "saturated pop colors against mundane neutrals"],
            lighting: ["mixed practical and stylized sources", "high-key to neon transitions"],
            lens: ["rapid perspective changes", "wide-angle and fisheye bursts", "kinetic camera movement"],
            texture: ["internet-age collage texture", "tactile everyday details", "controlled glitch accents"],
            atmosphere: ["manic energy", "absurd tenderness", "multiverse wonder"],
        },
        avoid: ["single monotonous visual treatment", "uncontrolled artifact noise", "empty spectacle"],
    }),
    directorPreset({
        id: "jonathan-glazer",
        label: "冷静凝视",
        inspiration: "受 Jonathan Glazer 的客观摄影、固定机位与日常恐怖并置启发",
        tags: ["客观", "固定机位", "冷漠"],
        fragments: {
            composition: ["fixed surveillance-like framing", "distant observational composition", "stark everyday-horror juxtaposition"],
            palette: ["extreme desaturation", "cold neutral palette", "restrained greens"],
            lighting: ["flat available light", "unembellished practical sources"],
            lens: ["static locked camera", "neutral long-lens viewpoint"],
            texture: ["unpolished documentary grain", "ordinary surface detail"],
            atmosphere: ["detached witness", "banal dread", "silent contrast"],
        },
        avoid: ["melodramatic lighting", "heroic camera movement", "glamour retouching"],
    }),
    directorPreset({
        id: "quentin-tarantino",
        label: "类型暴力",
        inspiration: "受 Quentin Tarantino 的类型混搭、环形调度与风格化冲突启发",
        tags: ["类型混搭", "暴力", "低角度"],
        fragments: {
            composition: ["circular blocking in dialogue scenes", "genre-mixed visual staging", "deliberate low-angle inserts"],
            palette: ["bold genre-coded colors", "saturated red and yellow", "high-contrast pulp palette"],
            lighting: ["hard stylized practical light", "neon and noir light pools"],
            lens: ["low-angle widescreen perspective", "long-take camera movement", "dynamic action framing"],
            texture: ["tactile pulp surfaces", "restrained 35mm grain"],
            atmosphere: ["playful menace", "kinetic pulp energy", "stylized confrontation"],
        },
        avoid: ["anonymous flat staging", "soft corporate palette", "weightless action"],
    }),
    directorPreset({
        id: "danny-boyle",
        label: "高能动感",
        inspiration: "受 Danny Boyle 的手持动感、高饱和色彩与音乐蒙太奇启发",
        tags: ["高能", "手持", "蒙太奇"],
        fragments: {
            composition: ["kinetic off-axis framing", "compressed urban staging", "subjective close-up perspective"],
            palette: ["highly saturated gold, orange, and green", "energetic complementary accents"],
            lighting: ["high-energy mixed practical light", "hard colored side light"],
            lens: ["handheld wide-angle perspective", "rapid whip-pan movement", "kinetic camera"],
            texture: ["gritty 35mm grain", "urban tactile surfaces"],
            atmosphere: ["urgent momentum", "music-driven energy", "visceral immediacy"],
        },
        avoid: ["over-stabilized stillness", "muted lifeless palette", "clean showroom surfaces"],
    }),
    directorPreset({
        id: "hayao-miyazaki",
        label: "手绘自然",
        inspiration: "受 Hayao Miyazaki 的手绘温度、自然细节与诗意探索启发",
        tags: ["手绘", "自然", "诗意"],
        fragments: {
            composition: ["environmental storytelling", "quiet foreground details", "natural asymmetry"],
            palette: ["warm hand-painted colors", "lush greens", "gentle sky blues"],
            lighting: ["soft natural light", "dappled sunlight", "magical ambient glow"],
            lens: ["gentle wide perspective", "slow exploratory camera"],
            texture: ["hand-painted brush texture", "tactile natural details", "subtle analog grain"],
            atmosphere: ["poetic wonder", "humane warmth", "whispering nature"],
        },
        avoid: ["cold sterile CGI", "aggressive contrast", "generic fantasy armor"],
    }),
    directorPreset({
        id: "sofia-coppola",
        label: "霓虹孤独",
        inspiration: "受 Sofia Coppola 的极简空间、柔和霓虹与孤独感启发",
        tags: ["极简", "孤独", "霓虹"],
        fragments: {
            composition: ["minimal clean framing", "spacious corridors", "centered solitary figure"],
            palette: ["muted pastel tones", "soft neon city accents", "restrained pinks"],
            lighting: ["soft ambient city light", "gentle practical glow", "low-contrast illumination"],
            lens: ["static or slow dolly movement", "shallow depth of field"],
            texture: ["delicate film grain", "clean tactile interiors"],
            atmosphere: ["quiet alienation", "longing", "introspective stillness"],
        },
        avoid: ["busy maximalist décor", "hard theatrical light", "forced expressive posing"],
    }),
    directorPreset({
        id: "edward-berger",
        label: "战壕冷峻",
        inspiration: "受 Edward Berger 的去浪漫化战争、冷灰蓝与压迫空间启发",
        tags: ["战争", "冷灰蓝", "压迫"],
        fragments: {
            composition: ["claustrophobic trench framing", "low-angle perspective", "lateral tracking through compressed space"],
            palette: ["cold gray-blue", "muddy desaturation", "restrained earth tones"],
            lighting: ["bleak overcast natural light", "sudden high-contrast flash light"],
            lens: ["handheld wide-angle", "lateral tracking", "intimate close perspective"],
            texture: ["mud, smoke, and wet fabric", "gritty film grain"],
            atmosphere: ["de-romanticized war", "exhausted dread", "sudden violent rupture"],
        },
        avoid: ["heroic glossy war imagery", "clean untouched uniforms", "cheerful color grade"],
    }),
];

export const IMAGE_STYLE_PRESETS = [...BASE_IMAGE_STYLE_PRESETS, ...ADDITIONAL_IMAGE_STYLE_PRESETS] satisfies readonly ImageStylePreset[];

const BASE_IMAGE_STYLE_GENRES = [
    {
        id: "film-noir",
        label: "黑色电影",
        family: "genre",
        tags: ["低调光", "硬阴影", "悬疑"],
        fragments: fragments({
            composition: ["oblique framing", "deep corridors of shadow", "strong silhouette separation"],
            palette: ["near-monochrome charcoal tones", "restrained silver highlights"],
            lighting: ["low-key lighting", "venetian-blind shadow pattern", "hard motivated backlight"],
            lens: ["35mm street perspective", "measured dolly-in"],
            texture: ["high-contrast black-and-white film grain"],
            atmosphere: ["moral ambiguity", "suspenseful nocturnal mood"],
        }),
        avoid: ["bright cheerful fill light", "flat gray image", "clean advertising polish"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / crime and noir" },
    },
    {
        id: "science-fiction",
        label: "科幻史诗",
        family: "genre",
        tags: ["未来", "尺度", "工业"],
        fragments: fragments({
            composition: ["monumental architecture framing", "human figure used for scale", "clean geometric perspective"],
            palette: ["cool steel and graphite tones", "controlled cyan and amber accents"],
            lighting: ["volumetric industrial light", "precise rim lighting", "practical illuminated surfaces"],
            lens: ["wide-format perspective", "slow precise camera movement"],
            texture: ["machined metal and worn material detail"],
            atmosphere: ["grounded futuristic realism", "vast unknown environment"],
        }),
        avoid: ["generic space opera clutter", "neon color overload", "weightless plastic surfaces"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / science fiction" },
    },
    {
        id: "period-drama",
        label: "历史年代剧",
        family: "genre",
        tags: ["年代", "布景", "自然光"],
        fragments: fragments({
            composition: ["formal tableau composition", "layered period interiors", "context-rich environmental framing"],
            palette: ["muted earth tones", "aged warm highlights", "period-appropriate color restraint"],
            lighting: ["candle or window motivated light", "soft falloff", "sculpted interior shadows"],
            lens: ["classic spherical lens rendering", "slow composed movement"],
            texture: ["woven fabric, wood, and patina detail", "subtle archival grain"],
            atmosphere: ["lived-in historical authenticity", "quiet social observation"],
        }),
        avoid: ["modern plastic materials", "contemporary signage", "oversaturated digital color"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / historical drama" },
    },
    {
        id: "romantic-drama",
        label: "浪漫剧情",
        family: "genre",
        tags: ["人物", "柔光", "情绪"],
        fragments: fragments({
            composition: ["intimate two-shot framing", "gentle visual eye-lines", "meaningful environmental detail"],
            palette: ["warm skin tones", "soft complementary colors", "restrained romantic highlights"],
            lighting: ["soft motivated window light", "subtle backlight", "gentle practical bokeh"],
            lens: ["natural 50mm perspective", "slow intimate push-in"],
            texture: ["natural skin texture", "fine soft film grain"],
            atmosphere: ["tender emotional tension", "observed human intimacy"],
        }),
        avoid: ["plastic skin smoothing", "excessive lens bloom", "generic stock-photo posing"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / romance and drama" },
    },
    {
        id: "documentary-realism",
        label: "纪实现实主义",
        family: "genre",
        tags: ["真实", "现场", "自然"],
        fragments: fragments({
            composition: ["observational handheld framing", "unposed human interactions", "authentic environmental context"],
            palette: ["true-to-life subdued colors", "natural skin tones", "available-light contrast"],
            lighting: ["available natural light", "practical interior sources", "unpolished exposure variation"],
            lens: ["documentary 35mm viewpoint", "responsive handheld movement"],
            texture: ["real surface imperfections", "fine documentary grain"],
            atmosphere: ["immediate lived reality", "quiet human detail"],
        }),
        avoid: ["posed commercial smiles", "perfect studio lighting", "synthetic CGI texture"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / documentary and realism" },
    },
    {
        id: "dark-fantasy",
        label: "暗黑奇幻类型",
        family: "genre",
        tags: ["幻想", "阴影", "寓言"],
        fragments: fragments({
            composition: ["symbolic prop foreground", "layered storybook staging", "slightly uncanny perspective"],
            palette: ["deep teal, umber, and muted crimson", "isolated warm highlights"],
            lighting: ["moody chiaroscuro", "hazy shafts of light", "motivated candle or moonlight"],
            lens: ["close wide-angle intimacy", "slow creeping movement"],
            texture: ["organic tactile materials", "subtle cinematic grain"],
            atmosphere: ["poetic menace", "fairy-tale mystery"],
        }),
        avoid: ["flat daylight", "generic fantasy game rendering", "gratuitous gore"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / fantasy and horror" },
    },
    {
        id: "coming-of-age",
        label: "成长青春",
        family: "genre",
        tags: ["青春", "自然光", "流动"],
        fragments: fragments({
            composition: ["close human-scale framing", "spontaneous group blocking", "open outdoor negative space"],
            palette: ["sun-washed natural colors", "gentle pastel accents", "seasonal color cues"],
            lighting: ["late-afternoon natural light", "soft window illumination", "honest shadow detail"],
            lens: ["light handheld 35mm perspective", "gentle roaming camera"],
            texture: ["light analog grain", "authentic everyday surfaces"],
            atmosphere: ["bittersweet discovery", "unforced youthful energy"],
        }),
        avoid: ["overly polished fashion editorial look", "artificial poses", "heavy beauty retouching"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / youth and coming of age" },
    },
] satisfies readonly ImageStyleGenre[];

const ADDITIONAL_IMAGE_STYLE_GENRES: readonly ImageStyleGenre[] = [
    {
        id: "drama",
        label: "剧情片",
        family: "genre",
        tags: ["表演", "写实", "情绪"],
        fragments: fragments({
            composition: ["performance-centered medium two-shot", "clear shot-reverse-shot dialogue staging", "emotional close-up at turning points"],
            palette: ["restrained naturalistic colors", "warm-to-cool emotional transition"],
            lighting: ["soft motivated natural light", "gentle high-contrast modeling"],
            lens: ["natural 50mm perspective", "slow emotional push-in"],
            texture: ["natural skin texture", "subtle organic film grain"],
            atmosphere: ["intimate human realism", "quiet emotional nuance"],
        }),
        avoid: ["melodramatic over-lighting", "generic stock posing", "plastic skin"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / drama" },
    },
    {
        id: "war",
        label: "战争片",
        family: "genre",
        tags: ["战场", "手持", "混乱"],
        fragments: fragments({
            composition: ["immersive handheld wide battle framing", "chaotic layered staging", "soldier-level subjective viewpoint"],
            palette: ["desaturated cold green-blue", "restrained blood-red accent"],
            lighting: ["high-contrast explosion light", "dust and smoke illuminated by practical sources"],
            lens: ["handheld 35mm wide angle", "shallow-focus close action"],
            texture: ["mud, dust, and smoke texture", "gritty 35mm grain"],
            atmosphere: ["combat immediacy", "confusion and dread"],
        }),
        avoid: ["heroic glossy war imagery", "clean untouched surfaces", "weightless action"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / war" },
    },
    {
        id: "epic-adventure",
        label: "史诗冒险片",
        family: "genre",
        tags: ["景观", "探索", "尺度"],
        fragments: fragments({
            composition: ["sweeping landscape establishing shot", "panorama-to-close-up scale rhythm", "tiny humans against vast nature"],
            palette: ["saturated natural colors or a controlled color script", "warm golden accents"],
            lighting: ["golden-hour natural light", "atmospheric haze, dust, and smoke"],
            lens: ["aerial establishing perspective", "Steadicam tracking", "telephoto distance compression"],
            texture: ["tactile practical-effects detail", "weathered natural surfaces"],
            atmosphere: ["heroic scale", "exploration and forward momentum"],
        }),
        avoid: ["flat empty landscapes", "generic game rendering", "unmotivated spectacle"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / epic and adventure" },
    },
    {
        id: "mystery-horror",
        label: "悬疑恐怖片",
        family: "genre",
        tags: ["不安", "阴影", "悬念"],
        fragments: fragments({
            composition: ["5-to-15-degree Dutch angle", "confined asymmetric framing", "subjective point of view with information asymmetry"],
            palette: ["desaturated cold tones", "isolated red accent"],
            lighting: ["chiaroscuro with large shadow areas", "isolated practical pools", "flickering light"],
            lens: ["slow suspenseful push-in", "sudden handheld bursts", "anamorphic horizontal flare"],
            texture: ["fine cinematic grain", "claustrophobic tactile surfaces"],
            atmosphere: ["impending threat", "psychological suspense", "quiet terror"],
        }),
        avoid: ["bright cheerful fill", "gratuitous gore", "predictable flat framing"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / mystery and horror" },
    },
    {
        id: "musical",
        label: "音乐歌舞片",
        family: "genre",
        tags: ["舞台", "节奏", "高饱和"],
        fragments: fragments({
            composition: ["full-body performance framing", "Cinemascope widescreen staging", "choreography-friendly group blocking"],
            palette: ["saturated deep blue, red, and pastel accents"],
            lighting: ["stage spotlights against a dark background", "colored practical stage light"],
            lens: ["flowing long take", "sweeping crane and tracking movement", "widescreen perspective"],
            texture: ["tactile stage surfaces", "subtle polished film grain"],
            atmosphere: ["rhythmic exuberance", "romantic spectacle", "music-synchronized energy"],
        }),
        avoid: ["cropped feet and hands", "flat office lighting", "muddy desaturation"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / musical and dance" },
    },
    {
        id: "western",
        label: "西部片",
        family: "genre",
        tags: ["荒野", "地平线", "边界"],
        fragments: fragments({
            composition: ["low or high horizon system", "doorway framing between civilization and wilderness", "wide landscape with isolated figure"],
            palette: ["desaturated ochre, brown, and gray-green", "sunset gold"],
            lighting: ["hard midday top light", "golden-hour side light", "strong silhouette separation"],
            lens: ["fixed wide establishing shot", "telephoto action compression"],
            texture: ["dust, weathered wood, and leather", "restrained 35mm grain"],
            atmosphere: ["frontier solitude", "moral boundary", "tense stillness"],
        }),
        avoid: ["modern signage", "clean untouched props", "flat horizon"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / western" },
    },
    {
        id: "surreal-art",
        label: "超现实艺术片",
        family: "genre",
        tags: ["梦境", "变形", "非线性"],
        fragments: fragments({
            composition: ["symmetric or radically asymmetric framing", "impossible architecture", "deliberate 180-degree rule breaking"],
            palette: ["oversaturated non-naturalistic colors", "psychological near-monochrome mapping"],
            lighting: ["flat even light removing depth cues", "non-natural high-contrast light"],
            lens: ["fisheye and wide-angle distortion", "extreme facial close-up", "Dutch-angle perspective"],
            texture: ["vintage film look", "tactile dreamlike surfaces"],
            atmosphere: ["liminal dream logic", "uncanny stillness", "nonlinear space and time"],
        }),
        avoid: ["literal realistic staging", "generic fantasy gloss", "random visual noise"],
        version,
        source: { ...IMAGE_STYLE_SOURCE, section: "genre guides / surreal and art cinema" },
    },
];

export const IMAGE_STYLE_GENRES = [...BASE_IMAGE_STYLE_GENRES, ...ADDITIONAL_IMAGE_STYLE_GENRES] satisfies readonly ImageStyleGenre[];

export const IMAGE_STYLE_DIMENSION_GROUPS: readonly { id: ImageStyleDimensionGroup; label: string; hint: string }[] = [
    { id: "composition", label: "构图技巧", hint: "主体位置、空间层次与画面秩序" },
    { id: "colorGrading", label: "调色方案", hint: "色调、饱和度、对比度与色温" },
    { id: "lighting", label: "光影方式", hint: "光源、阴影与氛围光" },
    { id: "lens", label: "镜头质感", hint: "焦段、景深与画幅观感" },
    { id: "cameraMovement", label: "运镜方式", hint: "镜头移动与观看节奏" },
    { id: "texture", label: "画面质感", hint: "胶片、材质与颗粒" },
    { id: "atmosphere", label: "氛围情绪", hint: "情绪、空气感与叙事气质" },
    { id: "editingRhythm", label: "剪辑节奏", hint: "图片也可用来控制视觉节奏" },
];

function dimensionOption(group: ImageStyleDimensionGroup, id: string, label: string, prompt: string, tags: readonly string[] = []): ImageStyleDimensionOption {
    return { group, id, label, prompt, ...(tags.length ? { tags } : {}) };
}

/** Practical, independently selectable controls distilled from the source skill. */
export const IMAGE_STYLE_DIMENSIONS = {
    composition: [
        dimensionOption("composition", "symmetry-center", "中心对称", "symmetrical composition, centered vanishing point, elements aligned on the central axis"),
        dimensionOption("composition", "thirds-negative-space", "三分法＋负空间", "rule-of-thirds composition, subject placed on a third, expansive negative space"),
        dimensionOption("composition", "frame-within-frame", "门框／框架", "framing within frame using doors, windows, or mirrors"),
        dimensionOption("composition", "deep-focus-staging", "深度构图", "deep staging with foreground, middle ground, and background all carrying information, wide lens, deep focus"),
        dimensionOption("composition", "low-angle-power", "低角度仰拍", "low-angle shot from near ground level, imposing perspective, power emphasis"),
    ],
    colorGrading: [
        dimensionOption("colorGrading", "cool-gray-red", "冷灰红点缀", "cool gray palette with restrained red accents, low saturation, high contrast, cool color temperature"),
        dimensionOption("colorGrading", "cold-blue-orange-fog", "冷蓝灰橙雾", "desaturated cold blue-gray palette with amber haze, very low saturation, very high contrast, 7000K+ cool color temperature"),
        dimensionOption("colorGrading", "warm-natural", "温暖自然", "warm natural palette, medium saturation, medium contrast, warm color temperature"),
        dimensionOption("colorGrading", "neon-night", "霓虹夜色", "neon-lit urban night palette, high saturation, high contrast, mixed color temperature"),
        dimensionOption("colorGrading", "blue-red-pink", "蓝红粉高饱和", "high-saturation deep blue, red, and pastel pink palette, medium-high contrast, warm-to-cool color shift"),
        dimensionOption("colorGrading", "pastel-earth", "粉彩大地", "pastel earth-tone palette, medium saturation, low contrast, neutral color temperature"),
        dimensionOption("colorGrading", "social-coded", "暖冷叙事编码", "deliberate warm-cool color separation with class-coded local contrast"),
        dimensionOption("colorGrading", "cold-blue-high-contrast", "冷蓝灰高反差", "cold blue-gray palette, low saturation, high contrast, cool color temperature"),
        dimensionOption("colorGrading", "high-low-key-weather", "高低调自然", "high-key and low-key contrast, medium saturation, very high contrast, natural color temperature"),
        dimensionOption("colorGrading", "natural-desaturated", "自然去饱和", "desaturated natural palette, low saturation, medium-high contrast, neutral color temperature"),
    ],
    lighting: [
        dimensionOption("lighting", "natural-available", "现场自然光", "available natural light with unmodified exposure variation"),
        dimensionOption("lighting", "golden-hour", "黄金时段侧光", "warm golden-hour side light with long sculpted shadows"),
        dimensionOption("lighting", "low-key-chiaroscuro", "低调明暗对照", "low-key chiaroscuro with large areas of controlled shadow"),
        dimensionOption("lighting", "volumetric-haze", "雾霭体积光", "volumetric light shafts through haze, smoke, or dust"),
        dimensionOption("lighting", "practical-motivated", "场景内光源", "motivated practical light sources visible in the scene"),
        dimensionOption("lighting", "soft-window", "柔和窗光", "soft bounced window light with gentle facial modeling"),
    ],
    lens: [
        dimensionOption("lens", "35mm-documentary", "35mm 纪实视角", "responsive 35mm documentary perspective with natural spatial relationships"),
        dimensionOption("lens", "wide-deep-focus", "广角深焦", "wide-angle lens with deep focus and clear environmental context"),
        dimensionOption("lens", "telephoto-compression", "长焦压缩", "telephoto compression that layers distant planes and isolates the subject"),
        dimensionOption("lens", "shallow-portrait", "浅景深肖像", "shallow depth of field with a gentle portrait perspective and soft background falloff"),
        dimensionOption("lens", "anamorphic-widescreen", "变形宽银幕", "anamorphic widescreen perspective with restrained horizontal flare"),
        dimensionOption("lens", "fisheye-distortion", "鱼眼变形", "fisheye wide-angle distortion used deliberately for psychological unease"),
    ],
    cameraMovement: [
        dimensionOption("cameraMovement", "dolly-zoom", "滑动变焦", "dolly zoom, simultaneous camera move and zoom, vertigo effect"),
        dimensionOption("cameraMovement", "long-tracking", "长跟拍", "long tracking shot, immersive continuous movement through space"),
        dimensionOption("cameraMovement", "slow-push-in", "缓慢推进", "slow deliberate push-in toward the subject, increasing pressure and focus"),
        dimensionOption("cameraMovement", "lateral-track", "横向跟拍", "precise lateral tracking, observational side-to-side movement"),
        dimensionOption("cameraMovement", "steadicam-orbit", "斯坦尼康环绕", "Steadicam orbit around the subject, exploratory encirclement"),
        dimensionOption("cameraMovement", "handheld-shake", "手持晃动", "handheld camera with restrained shake, immediate realism and chaos"),
        dimensionOption("cameraMovement", "locked-gaze", "固定凝视", "locked-off static gaze, objective surveillance-like observation"),
        dimensionOption("cameraMovement", "pseudo-one-take", "伪一镜到底", "pseudo-single-take continuity, seamless movement through connected spaces"),
    ],
    texture: [
        dimensionOption("texture", "35mm-grain", "35mm 胶片颗粒", "subtle 35mm film grain with organic photographic texture"),
        dimensionOption("texture", "70mm-clarity", "70mm 清晰度", "fine large-format grain with crisp physical detail"),
        dimensionOption("texture", "archival-grain", "年代档案颗粒", "restrained archival grain and gently softened contrast"),
        dimensionOption("texture", "wet-tactile", "湿润材质", "tactile wet surfaces, rain reflections, and believable material imperfections"),
        dimensionOption("texture", "dust-and-smoke", "尘土烟雾", "visible dust, smoke, and weathered surfaces integrated into the image"),
        dimensionOption("texture", "hand-painted", "手绘笔触", "warm hand-painted brush texture with tactile natural details"),
    ],
    atmosphere: [
        dimensionOption("atmosphere", "quiet-tension", "安静张力", "quiet tension and restrained dramatic pressure"),
        dimensionOption("atmosphere", "monumental-awe", "宏大敬畏", "monumental scale and contemplative awe"),
        dimensionOption("atmosphere", "nocturnal-grit", "夜行粗粝", "gritty nocturnal energy and immediate human presence"),
        dimensionOption("atmosphere", "poetic-unease", "诗意不安", "poetic unease with dark fairy-tale wonder"),
        dimensionOption("atmosphere", "intimate-human", "亲密人文", "intimate human warmth and emotionally observed realism"),
        dimensionOption("atmosphere", "surveillance-dread", "冷静恐惧", "detached witness perspective and banal dread"),
    ],
    editingRhythm: [
        dimensionOption("editingRhythm", "scorsese-rhythm", "音乐驱动动势", "music-driven montage energy, kinetic visual rhythm, freeze-frame emphasis"),
        dimensionOption("editingRhythm", "nolan-time-structure", "多线时间结构", "precise nonlinear time structure, parallel temporal layers, match-cut visual logic"),
        dimensionOption("editingRhythm", "hitchcock-suspense", "信息不对称悬念", "suspenseful information asymmetry, reveal danger before the subject, escalating visual rhythm"),
    ],
} satisfies Readonly<Record<ImageStyleDimensionGroup, readonly ImageStyleDimensionOption[]>>;

export const IMAGE_STYLE_DIMENSION_MAP = new Map(
    Object.values(IMAGE_STYLE_DIMENSIONS)
        .flat()
        .map((option) => [option.id, option]),
);

export const IMAGE_STYLE_PRESET_MAP = new Map(IMAGE_STYLE_PRESETS.map((preset) => [preset.id, preset]));
export const IMAGE_STYLE_GENRE_MAP = new Map(IMAGE_STYLE_GENRES.map((genre) => [genre.id, genre]));

export const DEFAULT_IMAGE_STYLE_SELECTION: ImageStyleSelection = {
    intensity: 0,
    preserveSubject: true,
};

export function resolveImageStylePreset(id?: string) {
    const key = typeof id === "string" ? id.trim().toLowerCase() : "";
    return key ? IMAGE_STYLE_PRESET_MAP.get(key) : undefined;
}

export function resolveImageStyleGenre(id?: string) {
    const key = typeof id === "string" ? id.trim().toLowerCase() : "";
    return key ? IMAGE_STYLE_GENRE_MAP.get(key) : undefined;
}
